In [9]:
import segmentation as sg
import pm4py as pm
import pandas as pd
import numpy as np
import os
from sklearn.feature_extraction.text import CountVectorizer
from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.objects.conversion.process_tree import converter as tree_to_petri
from pm4py.visualization.petri_net import visualizer as pn_visualizer
from pm4py.objects.log.util import dataframe_utils
from pm4py.objects.conversion.log import converter as log_converter
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import TruncatedSVD
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from pm4py.algo.conformance.alignments.petri_net import algorithm as alignments
from pm4py.algo.evaluation.precision import algorithm as precision_evaluator
from pm4py.statistics.traces.generic.log import case_statistics

In [10]:
path = os.path.join(os.getcwd(),'data', 'mimicel.csv')
df = pd.read_csv(path)

# Understanding Data

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7568824 entries, 0 to 7568823
Data columns (total 31 columns):
 #   Column             Dtype
---  ------             -----
 0   stay_id            int64
 1   subject_id         int64
 2   hadm_id            float64
 3   timestamps         object
 4   activity           object
 5   gender             object
 6   race               object
 7   arrival_transport  object
 8   disposition        object
 9   seq_num            float64
 10  icd_code           object
 11  icd_version        float64
 12  icd_title          object
 13  temperature        float64
 14  heartrate          float64
 15  resprate           float64
 16  o2sat              float64
 17  sbp                float64
 18  dbp                float64
 19  pain               object
 20  acuity             float64
 21  chiefcomplaint     object
 22  rhythm             object
 23  name               object
 24  gsn                float64
 25  ndc                float64
 26  etc_rn             float64
 27  etccode            float64
 28  etcdescription     object
 29  med_rn             float64
 30  gsn_rn             float64
dtypes: float64(16), int64(2), object(13)
memory usage: 1.7+ GB

In [12]:
df.head()

,stay_id,subject_id,hadm_id,timestamps,activity,gender,race,arrival_transport,disposition,seq_num,...,chiefcomplaint,rhythm,name,gsn,ndc,etc_rn,etccode,etcdescription,med_rn,gsn_rn
0,30000012,11714491,21562392.0,2126-02-14 20:22:00,Vital sign check,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30000012,11714491,21562392.0,2126-02-14 20:22:00,Enter the ED,F,WHITE,AMBULANCE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30000012,11714491,21562392.0,2126-02-14 20:22:01,Triage in the ED,NaN,NaN,NaN,NaN,NaN,...,CHANGE IN MENTAL STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,30000012,11714491,21562392.0,2126-02-14 22:21:00,Medicine reconciliation,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,rifaximin,66295.0,5.486862e+10,1.0,5844.0,Rifamycins and Related Derivative Antibiotics,NaN,NaN
4,30000012,11714491,21562392.0,2126-02-14 22:21:00,Medicine reconciliation,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"multivitamin,tx-minerals",2510.0,1.026707e+10,1.0,704.0,Multivitamin and Mineral Combinations,NaN,NaN